import Head from 'next/head'
import { DynaPuff } from "next/font/google"
import Herobalboa from '../components/Herobalboa'

const dyna = DynaPuff({
  subsets: ['latin'],
  variable: '--font-dyna',
})


export default function Home() {
  return (
    <>
      <Head>
        <title>Projeto dos guri</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${dyna.variable} bg-background min-h-screen`}>
        <Herobalboa />
      </main>
    </>
  )
}
